// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Unlocked.Client.Models
{
    /// <summary>The wanted status for the lock</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LockStatus
    {
        [EnumMember(Value = "locked")]
        #pragma warning disable CS1591
        Locked,
        #pragma warning restore CS1591
        [EnumMember(Value = "unlocked")]
        #pragma warning disable CS1591
        Unlocked,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
