// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Unlocked.Client.Locks.Item;
using Unlocked.Client.Locks.Unlock;
namespace Unlocked.Client.Locks
{
    /// <summary>
    /// Builds and executes requests for operations under \locks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LocksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The unlock property</summary>
        public global::Unlocked.Client.Locks.Unlock.UnlockRequestBuilder Unlock
        {
            get => new global::Unlocked.Client.Locks.Unlock.UnlockRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Unlocked.Client.locks.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Unlocked.Client.Locks.Item.WithLockItemRequestBuilder"/></returns>
        public global::Unlocked.Client.Locks.Item.WithLockItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("lockId", position);
                return new global::Unlocked.Client.Locks.Item.WithLockItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Unlocked.Client.locks.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Unlocked.Client.Locks.Item.WithLockItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Unlocked.Client.Locks.Item.WithLockItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("lockId", position);
                return new global::Unlocked.Client.Locks.Item.WithLockItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Unlocked.Client.Locks.LocksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/locks", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Unlocked.Client.Locks.LocksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/locks", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
